name: riverpod_news_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  http: ^1.3.0
  floor: ^1.5.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner:
  custom_lint:
  riverpod_generator: any
  riverpod_lint: any
  floor_generator: ^1.5.0

flutter:

  uses-material-design: true